### ISSUE TITLE
Suitability of Lilliput for writing to custom file type for graphics/drawing app

### ISSUE THREAD

**Issue by dvclmn** [jkolb/Lilliput#5]
Hi Justin,

Wasn't sure if a git issue was the right venue for getting in touch, as I don't have an issue ha — but do have a quick question.

I am working on a drawing and animation app for iPadOS. I'd like to read and write a proprietary document type, that contains all the image and other metadata needed for each canvas created etc. I am new to Swift, and learning as I go. From what I've gathered so far, zipping exported files up as binary (in chunks?) will be the best approach.

Is your library something that can provide a framework for doing this in my app?

I appreciate any guidance you can give.

Best,

Dave
hello@dvclmn.com

**Comment by jkolb** [comment]
You could use it for ideas, but I don’t think it is the best thing to use since it tries to be endian agnostic when a specific format would prefer to pick an endianess and write specific code for it.

**Comment by dvclmn** [comment]
Ah great, that’s really helpful to know. Thanks Justin!
